### ISSUE TITLE
inference error: KeyError: 'audio_model.model.encoder.pos_conv_embed.conv.parametrizations.weight.original0'

### ISSUE THREAD

**Issue by wzr1201** [whwjdqls/DEEPTalk#2]
hi, when I run the inference code, raised following error:

Traceback (most recent call last):
  File "/home/jovyan/wangzairan/projects/DEEPTalk/DEEPTalk/demo.py", line 240, in <module>
    main(args, DEMOTE_config)
  File "/home/jovyan/wangzairan/projects/DEEPTalk/DEEPTalk/demo.py", line 123, in main
    original_weights = DEMOTE_ckpt[name]
KeyError: 'audio_model.model.encoder.pos_conv_embed.conv.parametrizations.weight.original0'

how can I solve this problem

**Comment by whwjdqls** [comment]
Hi wzr1201,
We updated the inference and added the rendering code. 
If the issue persists, leave an additional comment! Thanks for the interest!

**Comment by dingbaojin** [comment]
> Hi wzr1201, We updated the inference and added the rendering code. If the issue persists, leave an additional comment! Thanks for the interest!

Hi there, I downloaded the code two days ago, and got the same error.

**Comment by xiatao1015** [comment]
Downgrading the version of torch to 1.12.1 works.
